### ISSUE TITLE
Missing  you so much

### ISSUE THREAD

**Issue by swagkarna** [Anlos0023/wifidoser#1]
Hi Bro this is swagakarna I am your very big follower in youtube and github....What happen to you i did not see any videos on youtube nor on github any repos.....

Please Do Reply....Missing you so much....Love from swagkarna

**Comment by Anlos0023** [comment]
Sorry bro! 
I'm available now...

**Comment by swagkarna** [comment]
> Sorry bro! I'm available now...

Oh nice lol😂😂😂
